### PR TITLE
Recipe App: Features Implementation & Testing

### PR DESCRIPTION
**Pull request by romans-adi**
I completed this project entirely on my own because I was unpaired from my partner during the week. The project was migrated (copied) because my partner removed the original repository, and the previous branches and commits are no longer accessible.

image

This combined pull request encompasses a wide range of feature implementations and testing efforts for the project. Below is a summarized list of the key features and improvements made:

## General:

- Created a `database` based on the `UML diagram` with proper `tables`, `indices`, and `relations`.
- Implemented models (`User`, `Recipe`, `Food`, `Recipe Food`) with appropriate associations.
- Added methods for `calculating food` quantities across recipes.
- Developed controllers (`Foods`, `Users`, `Recipes`, `Recipe Foods`, `Shopping List`) and set up `routes`.
- Designed a shared `navigation` view for easier app navigation.
- Enhanced the visual aspect of the project with `Tailwind CSS` styles.

## User Management:

- Established user `authentication` using `Devise` gem.
- Styled login and sign-up views with `Tailwind CSS`.
- Integrated `CanCanCan` for user `authorization`.
- Migrated the `role` column to the `user table` to set the `role` and `authorization rules`.
- Add `permissions` for recipe `modification` and `deletion` by `non-creators`.
- Enhanced error messages with `white text color`.
- Set `measurement units` constant array with predetermined units.
- Improved `flash messages` for better user feedback.

## Recipes:

- Created recipe `forms` and `views`.
- Developed a recipes controller for `creating`, `showing`, and `deleting` recipes.
- Added `Add Recipe` button.
- Improved the Recipe Show view with `toggle` button, `Generate Shopping List`, and `Add Ingredient` buttons.
- Implemented `delete` buttons for `recipes` with permission checks.

## Foods:

- Built a dedicated `Foods` controller with basic `CRUD` actions.
- Designed a `view` to display `food items` in a `table` format.
- Provided `actions` for food `name`, `measurement unit`, `price`.

## Ingredient Forms (Recipe Foods):

- Created `forms` for adding `new` ingredients and `editing quantities`.
- Added form elements for `specifying quantity` and `selecting a food item`.

## Shopping List:

- Added a `shopping list view` that `calculates` the total `number of food items` and their `total value`.
- Listed food items `to be purchased`, including `quantity` and `total value`.

## Testing:

- Conducted `unit tests` for `controllers` (Foods, Recipe Foods, Recipes, Shopping List).
- Performed `unit tests` for `models` (Food, Recipe Food, Recipe, User).
- Executed `integration tests` for various user interactions and scenarios.
- Ensured proper handling of user login, registration, and form validations.
- Implemented a `Login Helper` module for simulating user login in integration tests.
- Utilized `FactoryBot` for creating test data (users and recipes).

***
These changes collectively address the project's requirements, encompassing everything from database design and model associations to user authentication, authorization, and feature implementations. The tests ensure the robustness and reliability of the application. Additionally, the UI has been improved and personalized, adhering to wireframe designs while incorporating styling with Tailwind CSS.

Please note: The above descriptions are concise summaries of the key features and improvements made in this pull request. For more detailed information on each feature and testing, refer to the individual commits, previous pull requests and code changes.

The last issue/task and branch were created to fulfill an additional requirement unrelated to the core project requirements.

### CODE REVIEW

**Comment by NahnahAJ** [comment]
## Project Status: INVALIDATED :red_circle: 
Hi @romans-adi , 

While you made a great effort in this project, I can't go ahead and review your code.


## Invalid Code Review Request

- This is because you have submitted a project, that is a `group project` and as a result needs to be collaborated on by both you and your partner or partners.
- However, if for some reason you had to do the project alone, then kindly attach a screenshot of the message you received from Student Success stating that you can do the project alone :wink: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by NahnahAJ — APPROVED** [review]
## Project Status: APPROVED :green_circle: 
Hi @romans-adi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! Keep Rocking :100: 🎉 


## Highlights :fire: 
- Linters well setup and passing :heavy_check_mark: 
- Professional README :heavy_check_mark: 
- The application has a login and Registration page, built with the Devise gem :heavy_check_mark:
- Prevents `N+1 queries` problem from happening :heavy_check_mark: 
- All Project requirements met :heavy_check_mark: 
- Required tests included :heavy_check_mark:
- Wonderful design and good use of including notifications for users :fire:  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by romans-adi** [comment]
Oh, wow! You came back after a few hours to review it again! :tada:  Thank you so much, @NahnahAJ! I wish you a jolly day! :clinking_glasses:

**Comment by NahnahAJ** [comment]
You're welcome @romans-adi Very impressive work :wink:

**Pull request merged**
